name: Latest Chess Game

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  chess-game:
    name: Latest Lichess.org Game
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          base: ""
          filename: metrics.plugin.chess.svg
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_platform: lichess.org
          plugin_chess_user: ibrantes
